pipeline {
    agent any
    stages {
//         stage('Build') {
//             agent {
//                 docker {
//                     image 'node:16.3.0-alpine'
//                     // Run the container on the node specified at the
//                     // top-level of the Pipeline, in the same workspace,
//                     // rather than on a new node entirely:
//                     reuseNode true
//                 }
//             }
//             steps {
//                 sh 'npm install'
//                 sh 'npm run build'
//             }
//         }
        stage('Prep') {
            steps {
                sh 'touch ./deployment/.env'
                sh 'cp requirement.txt ./deployment/'
            }
        }
        stage('Deploy') {
         steps {
         dir('deployment') {
                         sh 'docker build -t wrh-brac:prd -f Dockerfile .'
                         sh "docker run -dt --restart=always -p 8010:8010 --name wrh-brac wrh-brac:prd"

         }

            }
//             agent {
//             dockerfile {
//                     dir './deployment'
//                     reuseNode true
//                  }
//              }
//             stages {
//                 stage('Test') {
//                     steps {
//                         sh 'node --version'
//                     }
//                 }
//             }
        }
    }
}