pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:16.3.0-alpine'
                    // Run the container on the node specified at the
                    // top-level of the Pipeline, in the same workspace,
                    // rather than on a new node entirely:
                    reuseNode true
                }
            }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Prep') {
            steps {
                sh 'cp .env ./deployment/'
                sh 'cp requirement.txt ./deployment/'
            }
        }
        stage('Deploy') {
         steps {
         dir('deployment') {
                         sh 'docker build -t wrh-brac:prd -f Dockerfile .'
                         script {
                          try {
                              sh 'docker rm -f wrh-brac'
                          } catch (Exception e) {
                              echo 'Exception occurred: ' + e.toString()
                          }
                          try {
                              sh ' docker run -dt --restart=always -p 8010:8010 --name wrh-brac wrh-brac:prd'
                          } catch (Exception e) {
                              echo 'Exception occurred: ' + e.toString()
                          }
                        }


         }

            }
//             agent {
//             dockerfile {
//                     dir './deployment'
//                     reuseNode true
//                  }
//              }
//             stages {
//                 stage('Test') {
//                     steps {
//                         sh 'node --version'
//                     }
//                 }
//             }
        }
    }
}