pipeline {
    agent {
        docker {
            image 'node:16.3.0-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'deployment/build.sh'
            }
        }
    }
}